name: terraform

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - "main"
      - "dev/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest

    # CLAVE: forzar environment para que el subject sea:
    # repo:hsniama/infra-devops:environment:dev o prod
    environment: ${{ (github.event_name == 'pull_request' || github.ref_name == 'main') && 'prod' || 'dev' }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Select env name
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" || "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend-config=../backends/${{ steps.env.outputs.env }}.hcl

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file=../environments/${{ steps.env.outputs.env }}.tfvars -out=plan.out

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ steps.env.outputs.env }}
          path: terraform/plan.out

  apply:
    needs: plan
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Select env name
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

      - name: Check backend storage account
        run: |
          az storage account show --name sttfstate2e9f0a4f --resource-group rg-tfstate-devops

      - name: Terraform init
        run: terraform init -backend-config=../backends/${{ steps.env.outputs.env }}.hcl

      - name: Terraform apply
        run: terraform apply -auto-approve -var-file=../environments/${{ steps.env.outputs.env }}.tfvars
